.. vim: ft=rst

.. Wheels2dmg
.. _wheels2dmg: https://github.com/matthew-brett/wheels2dmg
.. _wheels2dmg on travis-ci: https://travis-ci.org/matthew-brett/wheels2dmg
.. _wheels2dmg issue tracker:
    https://github.com/matthew-brett/wheels2dmg/issues
.. _wheels2dmg travis configuration:
    https://github.com/matthew-brett/wheels2dmg/blob/master/.travis.yml

.. Version control
.. _git: http://git-scm.com
.. _git parable: http://tom.preston-werner.com/2009/05/19/the-git-parable.html
.. _github: http://github.com
.. _bitbucket: https://bitbucket.org/

.. Editors
.. _vim: http://www.vim.org
.. _command-t: https://wincent.com/products/command-t
.. _command-t README: http://git.wincent.com/command-t.git/blob_plain/master:/README.txt

.. Python and common libraries
.. _python: http://www.python.org
.. _python.org: http://www.python.org
.. _python.org releases: http://www.python.org/download/releases
.. _distutils: http://docs.python.org/2/library/distutils.html
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://pypi.python.org/pypi/distribute
.. _pip: https://pip.pypa.io/en/latest/index.html
.. _pypa recommended: https://python-packaging-user-guide.readthedocs.org/en/latest/current.html
.. _Python packaging authority: https://www.pypa.io/en/latest/
.. _numpy: http://www.numpy.org
.. _scipy: http://www.scipy.org/scipylib/index.html
.. _matplotlib: http://matplotlib.org
.. _ipython: http://ipython.org
.. _pandas: http://pandas.pydata.org
.. _numexpr: https://github.com/pydata/numexpr
.. _sympy: http://www.sympy.org
.. _scipy stack: http://www.scipy.org/stackspec.html
.. _scikit-learn: http://scikit-learn.org
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes
.. _nose: http://readthedocs.org/docs/nose/en/latest
.. _nose-ipdb: https://github.com/flavioamieiro/nose-ipdb
.. _PyQT: http://www.riverbankcomputing.co.uk/software/pyqt/intro
.. _VTK: http://www.vtk.org

.. Virtualenv and helpers
.. _virtualenv: http://pypi.python.org/pypi/virtualenv
.. _virtualenvwrapper: http://www.doughellmann.com/projects/virtualenvwrapper
.. _old and new python versions: https://launchpad.net/%7Efkrull/+archive/deadsnakes

.. Pypi and packaging
.. _pypi: http://pypi.python.org
.. _example pypi: http://packages.python.org/an_example_pypi_project/setuptools.html#intermezzo-pypirc-file-and-gpg

.. Mac development
.. _github osx installation: http://help.github.com/mac-git-installation
.. _xcode: http://developer.apple.com/TOOLS/xcode
.. _macvim: https://github.com/b4winckler/macvim
.. _bdist_mpkg: http://pypi.python.org/pypi/bdist_mpkg
.. _parallels: http://www.parallels.com

.. Windows development
.. _mingw: http://www.mingw.org/wiki/Getting_Started
.. _msys: http://www.mingw.org/wiki/MSYS
.. _powershell: http://www.microsoft.com/powershell
.. _msysgit: http://code.google.com/p/msysgit
.. _putty: http://www.chiark.greenend.org.uk/~sgtatham/putty

.. Nipy and friends
.. _nipy: http://nipy.org
.. _gitwash: http://github.com/matthew-brett/gitwash

.. Licenses
.. _CC0 license: http://creativecommons.org/publicdomain/zero/1.0/legalcode

.. Testing:
.. _travis-ci: https://travis-ci.org

.. Friend pages
.. _docosx: http://matthew-brett.github.com/docosx
.. _developing on mac: http://matthew-brett.github.com/docosx/develop_mac.html
.. _booting macs: http://matthew-brett.github.com/docosx/booting_macs.html
.. _runtime linking on Mac:
    http://matthew-brett.github.com/docosx/mac_runtime_link.html
.. _osx legacy packaging redux:
    http://matthew-brett.github.com/docosx/osx_legacy_package_redux.html

.. Python and Mac
.. _which python: https://github.com/MacPython/wiki/wiki/Which-Python
.. _homebrew: http://brew.sh
.. _macports: https://www.macports.org
.. _Wheels: http://legacy.python.org/dev/peps/pep-0427
.. _xcode command line tools:
    https://developer.apple.com/library/ios/technotes/tn2339/_index.html

.. Other installers
.. _anaconda: https://store.continuum.io/cshop/anaconda
.. _Continuum analytics: http://www.continuum.io
.. _Conda: http://conda.pydata.org/docs/
.. _Enthought canopy: https://www.enthought.com/products/canopy/
.. _Enthought: https://www.enthought.com/
.. _Scipy SuperPack: http://fonnesbeck.github.io/ScipySuperpack

.. Substitutions
.. |emdash| unicode:: U+02014
.. |--| unicode:: U+2013   .. en dash
.. |---| unicode:: U+2014  .. em dash, trimming surrounding whitespace
   :trim:
